# https://github.com/siteshwar/centos-sync-packages/blob/d24dfb53ce26ac3415d57961664f86484a17735b/setup.sh
# Install package dependencies:
# - `git` is required to clone packages
# - `libcurl` is required to clone through `https` urls
# - Other packages are dependencies for pip modules
- name: "Install krb5-devel python3-devel, python3-pip, gcc, git and libcurl packages"
  yum:
    name: krb5-devel, python3-devel, python3-pip, gcc, git, libcurl
    state: latest

# These modules are required by script `centos-sync-packages` in git repo
- name: "Install koji and gitpython pip modules"
  pip:
    name: koji, gitpython
    executable: /usr/bin/pip3
  when: not ansible_check_mode

- name: "Install Red Hat certificate"
  yum:
    name: http://hdn.corp.redhat.com/rhel7-csb-stage/RPMS/noarch/redhat-internal-cert-install-0.1-15.el7.csb.noarch.rpm
    state: present

- name: "Setup rcm-tools-rhel-7-workstation.repo"
  template:
      src: "rcm-tools-rhel-7-workstation.repo.j2"
      dest: "/etc/yum.repos.d/rcm-tools-rhel-7-workstation.repo"

# `brew` command is used to download source package
- name: "Install rhpkg"
  yum:
    name: rhpkg
    state: latest
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Setup alt-src.repo"
  template:
      src: "alt-src.repo.j2"
      dest: "/etc/yum.repos.d/alt-src.repo"

# `alt-src` script is used to upload sources to CentOS Git repository
- name: "Install alt-src"
  yum:
    name: "python-alt-src"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"

# TODO: Shall we use some other path than `/tmp/stage` for `alt-src` script ?
- name: "Set up {{ ALTSRC_STAGE_DIR }}"
  file:
      name: "{{ ALTSRC_STAGE_DIR }}"
      state: directory
      owner: centos

# This template contains references to CentOS git repository and configurations for `alt-src` script
- name: "Copy /etc/altsrc.conf"
  template:
      src: "altsrc.conf.j2"
      dest: "/etc/altsrc.conf"

- name: "Set up {{ CENTOS_SYNC_PACKAGES_GITDIR }} directory"
  file:
      name: "{{ CENTOS_SYNC_PACKAGES_GITDIR }}"
      state: directory
      owner: centos

- name: "Set up centos-sync-packages repository"
  become: centos
  git:
    repo: https://github.com/siteshwar/centos-sync-packages.git
    dest: "{{ CENTOS_SYNC_PACKAGES_GITDIR }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Make the SSH private key directory"
  file:
    name: "/home/centos/.ssh"
    mode: 0700
    owner: centos
    state: directory

- name: "Set the SSH private key"
  copy:
    dest: "/home/centos/.ssh/id_rsa"
    src: "{{ sync2git_altsrc_ssh_private_key }}"
    mode: 0600
    owner: centos

- name: "Set the pagure api key"
  copy:
    content: "{{ sync2git_altsrc_pagure_apikey }}"
    dest: "/etc/altsrc-pagure.key"
    mode: 0600
    owner: centos

- name: "Set a proper email address in gitconfig for the altsrc user"
  become: centos
  git_config:
    name: user.email
    scope: global
    value: "bugs@centos.org"

- name: "Set a proper name gitconfig for the altsrc user"
  become: centos
  git_config:
    name: user.name
    scope: global
    value: "CentOS Sources"

# TODO: Shall we write a systemd service to automatically start the script when it's deployed ?

- name: "Message"
  debug:
      msg: "Now manually set up ssh keys under `~/.ssh` and run `python3 sync.py` from '{{ CENTOS_SYNC_PACKAGES_GITDIR }}' directory"
